profiles: desk -dev-java/jdbc-mysql
dev-java/jdbc-mysql depends on dev-java/ant-contrib which fail to build

>>> Preparing source in /var/tmp/portage/dev-java/ant-contrib-1.0_beta3-r2/work/ant-contrib ...
 * Applying tests-visibility.patch ...
 [ ok ]
Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
AttributeError: 'ElementTree' object has no attribute 'getiterator'